print('\n\n\n——————————————————————————————————————————————————————————\n欢迎来到简单购物商店！\n/list - 查看商品列表')
print('/list [Page] - 查看商品列表的指定页数')
print('/buy [Item ID] - 单独购买指定物品\n/addtocart [Item ID] - 添加一个指定物品到购物车')
print('/addtocart [Item ID] [Amount] - 添加多个指定物品到购物车')
print('/mycart - 查看购物车\n/check - 结账\n/quit - 退出系统\n——————————————————————————————————————————————————————————\n')